/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coordinates = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const Waypoint = IDL.Record({
  'labelText' : IDL.Opt(IDL.Text),
  'waypointType' : IDL.Variant({
    'checkpoint' : IDL.Null,
    'start' : IDL.Null,
    'finish' : IDL.Null,
    'obstacle' : IDL.Null,
    'standard' : IDL.Null,
  }),
  'radius' : IDL.Opt(IDL.Float64),
  'coordinates' : Coordinates,
});
export const RouteMetadata = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'difficulty' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'waypoints' : IDL.Vec(Waypoint),
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'updated' : IDL.Int,
  'length' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RouteSummary = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'difficulty' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'waypointCount' : IDL.Nat,
  'author' : IDL.Principal,
  'updated' : IDL.Int,
  'length' : IDL.Float64,
});
export const Route = IDL.Record({
  'id' : IDL.Text,
  'created' : IDL.Int,
  'difficulty' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'waypoints' : IDL.Vec(Waypoint),
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'updated' : IDL.Int,
  'length' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateRoute' : IDL.Func([RouteMetadata], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRoute' : IDL.Func([IDL.Text], [], []),
  'getAllRoutes' : IDL.Func([], [IDL.Vec(RouteSummary)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOldAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getRouteSummary' : IDL.Func([IDL.Text], [IDL.Opt(RouteSummary)], ['query']),
  'getRouteWithWaypoints' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RouteMetadata)],
      ['query'],
    ),
  'getRoutesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RouteSummary)],
      ['query'],
    ),
  'getRoutesByDifficulty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RouteSummary)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coordinates = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const Waypoint = IDL.Record({
    'labelText' : IDL.Opt(IDL.Text),
    'waypointType' : IDL.Variant({
      'checkpoint' : IDL.Null,
      'start' : IDL.Null,
      'finish' : IDL.Null,
      'obstacle' : IDL.Null,
      'standard' : IDL.Null,
    }),
    'radius' : IDL.Opt(IDL.Float64),
    'coordinates' : Coordinates,
  });
  const RouteMetadata = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'difficulty' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'waypoints' : IDL.Vec(Waypoint),
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'updated' : IDL.Int,
    'length' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RouteSummary = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'difficulty' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'waypointCount' : IDL.Nat,
    'author' : IDL.Principal,
    'updated' : IDL.Int,
    'length' : IDL.Float64,
  });
  const Route = IDL.Record({
    'id' : IDL.Text,
    'created' : IDL.Int,
    'difficulty' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'waypoints' : IDL.Vec(Waypoint),
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'updated' : IDL.Int,
    'length' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateRoute' : IDL.Func([RouteMetadata], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRoute' : IDL.Func([IDL.Text], [], []),
    'getAllRoutes' : IDL.Func([], [IDL.Vec(RouteSummary)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOldAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getRouteSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RouteSummary)],
        ['query'],
      ),
    'getRouteWithWaypoints' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RouteMetadata)],
        ['query'],
      ),
    'getRoutesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RouteSummary)],
        ['query'],
      ),
    'getRoutesByDifficulty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RouteSummary)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };