/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinates { 'x' : number, 'y' : number, 'z' : number }
export interface Route {
  'id' : string,
  'created' : bigint,
  'difficulty' : [] | [string],
  'name' : string,
  'waypoints' : Array<Waypoint>,
  'description' : string,
  'author' : Principal,
  'updated' : bigint,
  'length' : number,
}
export interface RouteMetadata {
  'id' : string,
  'created' : bigint,
  'difficulty' : [] | [string],
  'name' : string,
  'waypoints' : Array<Waypoint>,
  'description' : string,
  'author' : Principal,
  'updated' : bigint,
  'length' : number,
}
export interface RouteSummary {
  'id' : string,
  'created' : bigint,
  'difficulty' : [] | [string],
  'name' : string,
  'description' : string,
  'waypointCount' : bigint,
  'author' : Principal,
  'updated' : bigint,
  'length' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Waypoint {
  'labelText' : [] | [string],
  'waypointType' : { 'checkpoint' : null } |
    { 'start' : null } |
    { 'finish' : null } |
    { 'obstacle' : null } |
    { 'standard' : null },
  'radius' : [] | [number],
  'coordinates' : Coordinates,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateRoute' : ActorMethod<[RouteMetadata], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteRoute' : ActorMethod<[string], undefined>,
  'getAllRoutes' : ActorMethod<[], Array<RouteSummary>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOldAllRoutes' : ActorMethod<[], Array<Route>>,
  'getRouteSummary' : ActorMethod<[string], [] | [RouteSummary]>,
  'getRouteWithWaypoints' : ActorMethod<[string], [] | [RouteMetadata]>,
  'getRoutesByAuthor' : ActorMethod<[Principal], Array<RouteSummary>>,
  'getRoutesByDifficulty' : ActorMethod<[string], Array<RouteSummary>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];