/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Coordinates {
    x: number;
    y: number;
    z: number;
}
export interface RouteMetadata {
    id: string;
    created: bigint;
    difficulty?: string;
    name: string;
    waypoints: Array<Waypoint>;
    description: string;
    author: Principal;
    updated: bigint;
    length: number;
}
export interface Waypoint {
    labelText?: string;
    waypointType: Variant_checkpoint_start_finish_obstacle_standard;
    radius?: number;
    coordinates: Coordinates;
}
export interface RouteSummary {
    id: string;
    created: bigint;
    difficulty?: string;
    name: string;
    description: string;
    waypointCount: bigint;
    author: Principal;
    updated: bigint;
    length: number;
}
export interface Route {
    id: string;
    created: bigint;
    difficulty?: string;
    name: string;
    waypoints: Array<Waypoint>;
    description: string;
    author: Principal;
    updated: bigint;
    length: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_checkpoint_start_finish_obstacle_standard {
    checkpoint = "checkpoint",
    start = "start",
    finish = "finish",
    obstacle = "obstacle",
    standard = "standard"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateRoute(metadata: RouteMetadata): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteRoute(id: string): Promise<void>;
    getAllRoutes(): Promise<Array<RouteSummary>>;
    getCallerUserRole(): Promise<UserRole>;
    getOldAllRoutes(): Promise<Array<Route>>;
    getRouteSummary(id: string): Promise<RouteSummary | null>;
    getRouteWithWaypoints(id: string): Promise<RouteMetadata | null>;
    getRoutesByAuthor(author: Principal): Promise<Array<RouteSummary>>;
    getRoutesByDifficulty(difficulty: string): Promise<Array<RouteSummary>>;
    isCallerAdmin(): Promise<boolean>;
}
import type { Coordinates as _Coordinates, Route as _Route, RouteMetadata as _RouteMetadata, RouteSummary as _RouteSummary, UserRole as _UserRole, Waypoint as _Waypoint } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateRoute(arg0: RouteMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateRoute(to_candid_RouteMetadata_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateRoute(to_candid_RouteMetadata_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteRoute(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoute(arg0);
            return result;
        }
    }
    async getAllRoutes(): Promise<Array<RouteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoutes();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoutes();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOldAllRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOldAllRoutes();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOldAllRoutes();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRouteSummary(arg0: string): Promise<RouteSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRouteSummary(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRouteSummary(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRouteWithWaypoints(arg0: string): Promise<RouteMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRouteWithWaypoints(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRouteWithWaypoints(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutesByAuthor(arg0: Principal): Promise<Array<RouteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutesByAuthor(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutesByAuthor(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutesByDifficulty(arg0: string): Promise<Array<RouteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutesByDifficulty(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutesByDifficulty(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
}
function from_candid_RouteMetadata_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RouteMetadata): RouteMetadata {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RouteSummary_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RouteSummary): RouteSummary {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Route_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Route): Route {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Waypoint_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Waypoint): Waypoint {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RouteSummary]): RouteSummary | null {
    return value.length === 0 ? null : from_candid_RouteSummary_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RouteMetadata]): RouteMetadata | null {
    return value.length === 0 ? null : from_candid_RouteMetadata_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: bigint;
    difficulty: [] | [string];
    name: string;
    description: string;
    waypointCount: bigint;
    author: Principal;
    updated: bigint;
    length: number;
}): {
    id: string;
    created: bigint;
    difficulty?: string;
    name: string;
    description: string;
    waypointCount: bigint;
    author: Principal;
    updated: bigint;
    length: number;
} {
    return {
        id: value.id,
        created: value.created,
        difficulty: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.difficulty)),
        name: value.name,
        description: value.description,
        waypointCount: value.waypointCount,
        author: value.author,
        updated: value.updated,
        length: value.length
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: bigint;
    difficulty: [] | [string];
    name: string;
    waypoints: Array<_Waypoint>;
    description: string;
    author: Principal;
    updated: bigint;
    length: number;
}): {
    id: string;
    created: bigint;
    difficulty?: string;
    name: string;
    waypoints: Array<Waypoint>;
    description: string;
    author: Principal;
    updated: bigint;
    length: number;
} {
    return {
        id: value.id,
        created: value.created,
        difficulty: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.difficulty)),
        name: value.name,
        waypoints: from_candid_vec_n18(_uploadFile, _downloadFile, value.waypoints),
        description: value.description,
        author: value.author,
        updated: value.updated,
        length: value.length
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    labelText: [] | [string];
    waypointType: {
        checkpoint: null;
    } | {
        start: null;
    } | {
        finish: null;
    } | {
        obstacle: null;
    } | {
        standard: null;
    };
    radius: [] | [number];
    coordinates: _Coordinates;
}): {
    labelText?: string;
    waypointType: Variant_checkpoint_start_finish_obstacle_standard;
    radius?: number;
    coordinates: Coordinates;
} {
    return {
        labelText: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.labelText)),
        waypointType: from_candid_variant_n21(_uploadFile, _downloadFile, value.waypointType),
        radius: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.radius)),
        coordinates: value.coordinates
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkpoint: null;
} | {
    start: null;
} | {
    finish: null;
} | {
    obstacle: null;
} | {
    standard: null;
}): Variant_checkpoint_start_finish_obstacle_standard {
    return "checkpoint" in value ? Variant_checkpoint_start_finish_obstacle_standard.checkpoint : "start" in value ? Variant_checkpoint_start_finish_obstacle_standard.start : "finish" in value ? Variant_checkpoint_start_finish_obstacle_standard.finish : "obstacle" in value ? Variant_checkpoint_start_finish_obstacle_standard.obstacle : "standard" in value ? Variant_checkpoint_start_finish_obstacle_standard.standard : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Route>): Array<Route> {
    return value.map((x)=>from_candid_Route_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Waypoint>): Array<Waypoint> {
    return value.map((x)=>from_candid_Waypoint_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RouteSummary>): Array<RouteSummary> {
    return value.map((x)=>from_candid_RouteSummary_n10(_uploadFile, _downloadFile, x));
}
function to_candid_RouteMetadata_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RouteMetadata): _RouteMetadata {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Waypoint_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Waypoint): _Waypoint {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: bigint;
    difficulty?: string;
    name: string;
    waypoints: Array<Waypoint>;
    description: string;
    author: Principal;
    updated: bigint;
    length: number;
}): {
    id: string;
    created: bigint;
    difficulty: [] | [string];
    name: string;
    waypoints: Array<_Waypoint>;
    description: string;
    author: Principal;
    updated: bigint;
    length: number;
} {
    return {
        id: value.id,
        created: value.created,
        difficulty: value.difficulty ? candid_some(value.difficulty) : candid_none(),
        name: value.name,
        waypoints: to_candid_vec_n3(_uploadFile, _downloadFile, value.waypoints),
        description: value.description,
        author: value.author,
        updated: value.updated,
        length: value.length
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    labelText?: string;
    waypointType: Variant_checkpoint_start_finish_obstacle_standard;
    radius?: number;
    coordinates: Coordinates;
}): {
    labelText: [] | [string];
    waypointType: {
        checkpoint: null;
    } | {
        start: null;
    } | {
        finish: null;
    } | {
        obstacle: null;
    } | {
        standard: null;
    };
    radius: [] | [number];
    coordinates: _Coordinates;
} {
    return {
        labelText: value.labelText ? candid_some(value.labelText) : candid_none(),
        waypointType: to_candid_variant_n6(_uploadFile, _downloadFile, value.waypointType),
        radius: value.radius ? candid_some(value.radius) : candid_none(),
        coordinates: value.coordinates
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_checkpoint_start_finish_obstacle_standard): {
    checkpoint: null;
} | {
    start: null;
} | {
    finish: null;
} | {
    obstacle: null;
} | {
    standard: null;
} {
    return value == Variant_checkpoint_start_finish_obstacle_standard.checkpoint ? {
        checkpoint: null
    } : value == Variant_checkpoint_start_finish_obstacle_standard.start ? {
        start: null
    } : value == Variant_checkpoint_start_finish_obstacle_standard.finish ? {
        finish: null
    } : value == Variant_checkpoint_start_finish_obstacle_standard.obstacle ? {
        obstacle: null
    } : value == Variant_checkpoint_start_finish_obstacle_standard.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Waypoint>): Array<_Waypoint> {
    return value.map((x)=>to_candid_Waypoint_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
